### ISSUE TITLE
[User story] As a developer I want to return SCI scores so that I can calculate managed services

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/carbon-ql#10]
As a developer I want to return SCI scores so that I can calculate managed services

As discussed in this issue: https://github.com/Green-Software-Foundation/sci/discussions/235

For some things Carbon QL just needs to return an SCI score, e.g. for networking we don't want carbon ql to return separate E, I and M values, it's redundant, we just need to return an SCI score like Carbon / GB which you can then use to calculate your applications SCI score.

Networking is a managed service, you don't by the compute for networking you pay by some other param like GB.
Databases are another managed service.
Serverless are another managed service.

NOTE: To model this we can use some form of $ -> Carbon Emission Factor.

**Comment by srini1978** [comment]
@jawache One of  the idea for converting $ to Carbon emission factor is here https://www.cloudcarbonfootprint.org/docs/methodology#cloud-usage-and-cost-data-source
