### ISSUE TITLE
[User story] ....As a developer I would like to design my API without having the need for user to understand internal  details of SCI specs

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/carbon-ql#17]
As a developer I want to design a simple API for the end user so that the input parameters are provided without knowing a lot of details.

** Description **

For example, the user should just be able to give the software boundary environment specs, usage specs and duration of the workload in an easy format and all the internal parameters should be abstracted away . 

This is the customer facing API and should front end all internal APIs #9  and #6

**Comment by sebasrivera96** [comment]
@srini1978 - isn't this more a requirement for the whole CarbonQL project instead of a single User Store? IMO, we should have this idea in mind when developing any customer-facing components.
