### ISSUE TITLE
Design for the API

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/carbon-ql#2]
##  Requirements 

The carbonQL API may internally have 3 APIs.  

- Energy API  (E)  

- Marginal intensity API (I)
         
- Embodied emission API  

###  Energy API

Request message will be of the format  
```
{
          getEnergyCPU
               {
                   device type (cloud/laptop/non-cloud)
                   cloud provider name
                   OEM (in case of laptop - dell, HP)
                   region
                   number of vCPU
                  duration
                  durationunit
               }
            getEnergyStorage
                 {
                     device type (cloud/laptop/non-cloud)
                     cloud provider name
                       OEM (in case of laptop- dell,HP)
                     region
                     storage type (hdd/ssd)
                    storage usage
                   storage size unit (TB/GB/MB)
                    duration
                    durationunit
                 }
            getEnergyMemory
                 {
                     device type (cloud/laptop/non-cloud)
                     cloud provider name
                     OEM (in case of laptop- dell,HP)
                     region
                    memorytype (DDR4/DDR3/DDR5)
                    memoryusage
                   memory size unit (MB/GB)
                    duration
                    durationunit
                 }
                getEnergyNetworking
                     {
                          device type (cloud/laptop/non-cloud)
                          cloud provider name
                         region
                         data size
                         data size unit (KB/MB/GB)
                         duration (data transmission duration)
                         durationunit
                     }
}
```

###  Marginal Carbon Intensity API
  To get the marginal intensity value of the software. This is the increased carbon intensity value due to running of the software. For this we need to understand  
 a) Region and electricity grid where the hosting infrastructure of the software is getting it's power from   
b) the energy intensity mix of the grid  
 c) the duration for which the software is running or was running.    
    All these parameters should be passed into the API.   
            For example  
            a. Duration in minutes/hours.
           b.  The Cloud region where the software is hosted - central us, central India, us west 3 etc.  If it is an on-premise server or laptop/desktop, then this will be the carbon intensity value from the attached electricity grid. 
        The output from the API will be in gCo2eq/Hr.  
Request message will be of the format  
```
{
getCarbonIntensity  
     {
         grid region
         duration
     }
}
```
###  Embodied Emissions API

Request message will be of the format  
```
{
          getEmbodiedEmissionsCPU
               {
                   device type (cloud/laptop/non-cloud)
                   cloud provider name (aws/azure)
                   OEM (in case of laptop - dell, HP)
                   processorName
                    number of vCPU

               }
            getEmbodiedEmissionsStorage
                 {
                     device type (cloud/laptop/non-cloud)
                     cloud provider name
                     OEM (in case of laptop- dell,HP)
                     storage type (hdd/ssd)
                    storage size
                     storage size unit (TB/GB/MB)
                 }
            getEnergyMemory
                 {
                     device type (cloud/laptop/non-cloud)
                     cloud provider name
                     OEM (in case of laptop- dell,HP)
                    memorytype (DDR4/DDR3/DDR5)
                    memorysize
                   memory size unit (MB/GB)

                 }
                getEnergyNetworking
                     {
                          device type (cloud/laptop/non-cloud)
                          cloud provider name
                          region
                     }
}
```

**Comment by jawache** [comment]
@srini1978 this is why I like GraphQL as the framework for this project. GraphQL is like an API façade in front of multiple other "things", perfect when you want to create a single API that secretly behind it might have dozens, hundreds of other end points or bit of code that return data and it allows for flexibility on the calling side. When they make a call to the API they can request data in multiple different formats nested calls, all kinds of things. 

How our architecture would be built if it was in GraphQL is that we'd define resolvers, see: https://www.apollographql.com/docs/apollo-server/data/resolvers/. A resolver is like an atomic piece of code that returns one part of the API request, so we'd have a resolver for CarbonIntensity that takes some inputs and returns some responses.

Out of the box we might ship with a resolver for free public data.
If someone installs the WattTime package it adds a WattTime resolver to the chain and tries to use that first and if nothing is returns falls back to other resolvers in the chain.

If we can keep this in mind, I'm not 100% on this but my hunch is telling me this could be a good fit for this project.

**Comment by jawache** [comment]
The GitHub API is a GraphQL API, this is how you'd form requests to the API: https://docs.github.com/en/graphql/guides/forming-calls-with-graphql

**Comment by Oleg-Zhymolokhov** [comment]
@srini1978 we need to decide what we do with this issue and all related issues as we moved to framework/sdk creation and API-based approach is not we pursue now.

**Comment by jawache** [comment]
Hi @srini1978 I believe this issue can be closed now, the conversation has moved onwards and most of this is either incorporated into other docs/specs/conversations or has been superseded. Let me know if you want to reopen.
