### ISSUE TITLE
[User story] As an organization I want to make my private data available

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/carbon-ql#8]
As an organization I want to make my **private** data available through the Carbon QL so I can provide my customers who have an NDA more accurate data.

**Comment by Oleg-Zhymolokhov** [comment]
@jawache So does this mean we might want to create a more granular private (api-token based) API that will exist next to the public API?

**Comment by srini1978** [comment]
@Oleg-Zhymolokhov I believe this is related to an organization like one of the hyperscale cloud providers signing up with GSF to expose their private data through carbonQL

**Comment by jawache** [comment]
I think the easiest solution right now is:

1 - An open source solution the comes pre-configured with free open data sets anyone can use, they can host the API themselves or....
2 - We host a version of that solution on our own domain e.g. api.greensoftware.org which they can use.
3 - If a company wants to provide an enhanced version of the API with private data they close our repo, install/config their private data plugin, host it on their own site as api.anothercompany.org and make that avaiable to just their customers only.
