### ISSUE TITLE
[User story] ....As a developer I would like to build an API that returns Embodied emission value M

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/carbon-ql#9]
As a developer on the carbon QL project I want to build an API that returns embodied emissions value for the hardware components used so that this output can be used to calculate SCI value. 

** Input parameters **
The below parameters will be abstracted out as Key/Context/Usage

CPU name
RAM Type
RAM size
Storage size in GB
Number of HDDs
Number of SSDs

** Description **
This API will be able to internally leverage algorithms based on the input parameters given.

For example 
Key: SCI/GHG - this is the protocol used for calculation of the embodied emissions .Default value will be SCI.
Context : The context is the important parameter by which API internally decides which API or database to call. For example if the context has values like Laptop/Dell/HP then it will call another API or OEM database . If the Context has values similar to the instance names of VMs in a cloud provider or VM family names given in https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/tree/main/output then it makes a call to the cloud carbon co-efficient dataset.
Usage: 
The usage indicates the sizes that helps the API understand more context about the calling function . For example RAM size, HDD size, Number of vCPU cores that determines the size of the component for which embodied emissions can be calculated.

** Output **
Embodied emissions value in kgCo2 eq

**Comment by sebasrivera96** [comment]
@srini1978 - a quick clarification question... does key/context/usage needs to be provided for each component, i.e. CPU, RAM, HDD, SSD, etc.? Or it is a general input by the user? 

A `JSON` formatted input would be useful to better understand this User Story.

**Comment by sebasrivera96** [comment]
Oh, I see it is better described here https://github.com/Green-Software-Foundation/carbon-ql/issues/2 with an example.

**Comment by Oleg-Zhymolokhov** [comment]
@srini1978 After latest discussions and CQL design being in place do you think this user-story is up-to-date? As I understand, now if we even provide this functionality, this will be a function call that will calculate M for existing architecture based on Ontology?
